const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const admissionSchema = new Schema({
  Name: { type: String, required: true },
  CNIC: { type: String, required: true },
  Regno: { type: String, required: true },
  Enail: { type: String, required: true },
  Phone: { type: String, required: true },
  Familylanguage: { type: String, required: true },
  Nationality: { type: String, required: true },
  DoB: { type: String, required: true },
  Gender: { type: String, required: true },
  CAddress: { type: String, required: true },
  PAddress: { type: String, required: true },
  Applyingfor: { type: String, required: true },
  FStatus: { type: String, required: true },
  FName: { type: String, required: true },
  FEmail: { type: String, required: true },
  FPhone: { type: String, required: true },
  FOfficeNO: { type: String, required: true },
  FCNIC: { type: String, required: true },
  FBAddress: { type: String, required: true },
  FOccution: { type: String, required: true },
  FIndustry: { type: String, required: true },
  MStatus: { type: String, required: true },
  MName: { type: String, required: true },
  MEmail: { type: String, required: true },
  MPhone: { type: String, required: true },
  MOfficeNO: { type: String, required: true },
  MCNIC: { type: String, required: true },
  MBAddress: { type: String, required: true },
  MOccution: { type: String, required: true },
  MIndustry: { type: String, required: true },
  Sname: { type: String, required: true },
  Relationship: { type: String, required: true },
  Age: { type: String, required: true },
  NOI: { type: String, required: true },
  CPname: { type: String, required: true },
  Ephone: { type: String, required: true },
  CpRelationship: { type: String, required: true },
  Subject1: { type: String, required: true },
  Subject2: { type: String, required: true },
  Subject3: { type: String, required: true },
  Subject4: { type: String, required: true },
  Acc: { type: String, required: true },
  Eco: { type: String, required: true },
  Bus: { type: String, required: true },
  Math: { type: String, required: true },
  Phy: { type: String, required: true },
  Che: { type: String, required: true },
  Bio: { type: String, required: true },
  Soc: { type: String, required: true },
  Cs: { type: String, required: true },
  Englit: { type: String, required: true },
  Englag: { type: String, required: true },
  PS: { type: String, required: true },
  Addmath: { type: String, required: true },
  Urdu: { type: String, required: true },
  Isl: { type: String, required: true },
  EM: { type: String, required: true },
  CareerChoice: { type: String, required: true },
  ExCurricular: { type: String, required: true },
  Sports: { type: String, required: true },
  Responsiblites: { type: String, required: true },
  ShortParah: { type: String, required: true },
  Health: { type: String, required: true },
  CredoCollage: { type: String, required: true },
  AddmissionCredoCollage: { type: String, required: true },
  SiblingCredoCollage: { type: String, required: true },
}, {
  timestamps: true,
});

const Admission = mongoose.model('Admission', admissionSchema);

module.exports = Admission;